beta <- feature/add_project_structure
Dima418/employee-knowledge-quiz pull request #1
Opened 2022-07-04 16:19 UTC by Dima418

2022-07-04 18:00 UTC, Rybasher requested changes

2022-07-04 18:00 UTC, Rybasher commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/python,visualstudiocode,venv,git
Здорово, что ты добавил всё, что было в примере, но нам так много не надо

2022-07-04 18:00 UTC, Rybasher commented on requirements.txt
> +websockets==10.3
у тебя добавились зависимости из других проектов, создавай виртуальное окружение пж

2022-07-04 18:00 UTC, Rybasher commented on main.py
> +@app.get("/")
скину ссылку по норм структуре, глянешь

2022-07-05 09:00 UTC, Dima418 commented on .gitignore
> +# End of https://www.toptal.com/developers/gitignore/api/python,visualstudiocode,venv,git
Файл .gitignore генерируется с помощью веб-сервиса .gitignore.io. Данный веб-сервис, предназначенный для  быстрого и эфективного способа создания файлов .gitignore для репозиториев Git, включая особенности языка программирования или IDE.

https://github.com/toptal/gitignore.io

2022-07-05 09:03 UTC, Dima418 commented on requirements.txt
> +websockets==10.3
Зависимости для работы данного проекта были загружены в качестве рекомендуемой конфигурации, предложеной в документации к фреймворку FastAPI разработчиками.

https://fastapi.tiangolo.com/tutorial/

2022-07-05 09:09 UTC, Dima418 commented on main.py
> +@app.get("/")
Содержимое файла было переделано в пользу использования генератора приложений и вынесения ендпоитов в отдельные файлы с роутерами.

2022-07-05 10:29 UTC, Rybasher approved these changes

2022-07-05 10:30 UTC, merged